FROM node:25-alpine

WORKDIR /app

RUN npm install -g npm@latest

COPY package*.json ./
RUN npm install

COPY . .

RUN npm run postinstall

EXPOSE 3000

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
