<template>
  <div class="min-h-screen">
    <section class="relative pt-32 overflow-hidden h-screen">
      <div class="container mx-auto px-6">
        <div class="max-w-4xl mx-auto text-center">
          <h1 class="text-6xl md:text-7xl font-bold mb-8 leading-tight animate-fade-in">
            <span class="bg-gradient-to-r from-white via-purple-300 to-blue-200 bg-clip-text text-transparent">
              The Architecture of the Future,
            </span>
            <br />
            <span class="bg-gradient-to-r from-blue-300 via-purple-300 to-white bg-clip-text text-transparent">
              Generated by AI
            </span>
          </h1>
          <p class="text-xl mb-12 leading-relaxed max-w-2xl mx-auto">
            Instantly transform your images into precise 3D architectural models thanks to our cutting-edge AI.
          </p>
          <div class="flex flex-col sm:flex-row items-center justify-center gap-6">
            <Button size="lg" class="sm:w-auto">
              <Icon name="line-md:pause-to-play-filled-transition"/>
              View demo
            </Button>
            <Button size="lg" variant="outline" class="w-full sm:w-auto">
              Find out more
            </Button>
          </div>
        </div>
      </div>
    </section>

    <section class="py-20 relative">
      <div class="container mx-auto px-6">
        <h2 class="text-4xl font-bold text-center mb-16 bg-gradient-to-r from-white to-purple-400 bg-clip-text text-transparent">
          Une Révolution dans la Conception Architecturale
        </h2>
        <div class="grid md:grid-cols-3 gap-8">
          <i-card v-for="feature in features" :key="feature.title" 
            class="backdrop-blur-lg bg-white/5 border-white/10 hover:bg-white/10 transition-all duration-300">
            <div class="p-6">
              <div class="w-14 h-14 rounded-2xl bg-gradient-to-br from-purple-500 to-blue-500 flex items-center justify-center mb-6">
                <i-icon :name="feature.icon" size="24" />
              </div>
              <h3 class="text-xl font-bold mb-3">{{ feature.title }}</h3>
              <p class="text-gray-400">{{ feature.description }}</p>
            </div>
          </i-card>
        </div>
      </div>
    </section>


    <section class="py-20 relative bg-gradient-to-b from-transparent via-purple-900/20 to-transparent">
      <div class="">
        <h2 class="text-4xl font-bold text-center mb-16 bg-gradient-to-r from-white to-purple-400 bg-clip-text text-transparent">
          Ils Nous Font Confiance
        </h2>
        <div class="relative flex h-[500px] flex-col items-center justify-center overflow-hidden">
          <!-- First Marquee -->
          <Marquee pause-on-hover class="[--duration:40s]">
            <ReviewCard v-for="review in firstRow" :key="review.username" :img="review.img" :name="review.name"
              :username="review.username" :body="review.body" />
          </Marquee>

          <!-- Second Marquee (reverse) -->
          <Marquee reverse pause-on-hover class="[--duration:40s]">
            <ReviewCard v-for="review in secondRow" :key="review.username" :img="review.img" :name="review.name"
              :username="review.username" :body="review.body" />
          </Marquee>

          <!-- Left Gradient -->
          <div class="pointer-events-none absolute inset-y-0 left-0 w-1/3 bg-gradient-to-r from-white dark:from-background">
          </div>

          <!-- Right Gradient -->
          <div
            class="pointer-events-none absolute inset-y-0 right-0 w-1/3 bg-gradient-to-l from-white dark:from-background">
          </div>
        </div>
      </div>
    </section>


    <section class="py-20">
      <div class="container mx-auto px-6">
        <div class="relative rounded-3xl overflow-hidden">
          <div class="absolute inset-0 bg-gradient-to-r from-purple-600/20 to-blue-600/20 backdrop-blur-3xl"></div>
          <div class="relative p-12 text-center">
            <h2 class="text-4xl font-bold mb-6 bg-gradient-to-r from-white to-purple-400 bg-clip-text text-transparent">
              Prêt à Révolutionner Votre Workflow ?
            </h2>
            <p class="text-xl text-gray-300 mb-8 max-w-2xl mx-auto">
              Rejoignez des milliers d'architectes qui transforment déjà leur vision en réalité avec ArchVision AI.
            </p>
            <i-button size="lg">
              Commencer Gratuitement
            </i-button>
          </div>
        </div>
      </div>
    </section>

    <div>
      <StaticLogoCloud :logos title="Sponsored By" />
    </div>
  </div>
</template>

<script lang="ts" setup>
import StaticLogoCloud from "~/components/inspira-ui/animated-logo-cloud/StaticLogoCloud.vue";
import Marquee from "~/components/inspira-ui/marquee/Marquee.vue";
import ReviewCard from "~/components/inspira-ui/marquee/ReviewCard.vue";

const logos = [
  {
    name: "Stackoverflow",
    path: "https://res.cloudinary.com/dfhp33ufc/image/upload/v1715276558/logos/ts1j4mkooxqmscgptafa.svg",
  },
  {
    name: "mistral",
    path: "https://res.cloudinary.com/dfhp33ufc/image/upload/v1715276558/logos/tyos2ayezryjskox3wzs.svg",
  },
  {
    name: "Blender",
    path: "https://www.blender.org/wp-content/uploads/2020/07/blender_logo_no_socket_black.png",
  },
  {
    name: "Dassault Systèmes",
    path: "https://www.3ds.com/statics/menu/2/assets/img/logo/3ds-dark.svg",
  },
  {
    name: "Vercel",
    path: "https://res.cloudinary.com/dfhp33ufc/image/upload/v1715881430/vercel_wordmark_dark_mhv8u8.svg",
  },
  {
    name: "Prime",
    path: "https://res.cloudinary.com/dfhp33ufc/image/upload/v1715276558/logos/t2awrrfzdvmg1chnzyfr.svg",
  },
  {
    name: "Trustpilot",
    path: "https://res.cloudinary.com/dfhp33ufc/image/upload/v1715276558/logos/tkfspxqmjflfllbuqxsi.svg",
  },
  {
    name: "Webflow",
    path: "https://res.cloudinary.com/dfhp33ufc/image/upload/v1715276560/logos/nymiivu48d5lywhf9rpf.svg",
  },
];


// Reviews data
const reviews = [
  {
    name: "Sophie Martin",
    username: "@sophie_martin",
    body: "VizHome est une révolution dans le domaine de la modélisation 3D. Sa capacité à transformer des images et des descriptions textuelles en modèles 3D précis est impressionnante. Un outil indispensable pour les designers et les architectes.",
    img: "./images/humain/personne-1.jpg",
  },
  {
    name: "Lucas Dupont",
    username: "@lucas_duciel",
    body: "En tant que développeur de jeux vidéo, VizHome a simplifié mon flux de travail. La génération rapide de modèles 3D à partir de simples descriptions textuelles m'a fait gagner un temps précieux. Hautement recommandé !",
    img: "./images/humain/personne-2.jpg",
  },
  {
    name: "Emma Lefèvre",
    username: "@emma_creative",
    body: "L'interface intuitive de VizHome et sa précision dans la modélisation 3D en font un outil exceptionnel. Que ce soit à partir d'une image ou d'un texte, les résultats sont toujours au rendez-vous.",
    img: "./images/humain/personne-3.jpg",
  },
  {
    name: "Thomas Bernard",
    username: "@thomas_innov",
    body: "VizHome a dépassé mes attentes. La qualité des modèles 3D générés est remarquable, et la possibilité de travailler à partir de descriptions textuelles ouvre de nouvelles perspectives créatives.",
    img: "./images/humain/personne-4.jpg",
  },
  {
    name: "Camille Dubois",
    username: "@camille_design",
    body: "Pour tous ceux qui cherchent à intégrer rapidement des modèles 3D dans leurs projets, VizHome est la solution idéale. Sa technologie basée sur l'IA est à la fois puissante et facile à utiliser.",
    img: "./images/humain/personne-5.jpg",
  },
  {
    name: "Antoine Moreau",
    username: "@antoine_art",
    body: "La capacité de VizHome à convertir des descriptions textuelles en modèles 3D précis est tout simplement incroyable. C'est un outil révolutionnaire pour les créateurs de contenu.",
    img: "./images/humain/personne-6.jpg",
  },
  {
    name: "Julie Laurent",
    username: "@julie_archi",
    body: "VizHome est une révolution dans le domaine de la modélisation 3D. Sa capacité à transformer des images et des descriptions textuelles en modèles 3D précis est impressionnante. Un outil indispensable pour les designers et les architectes.",
    img: "./images/humain/personne-7.jpg",
  },
  {
    name: "Maxime Petit",
    username: "@maxime_dev",
    body: "En tant que développeur de jeux vidéo, VizHome a simplifié mon flux de travail. La génération rapide de modèles 3D à partir de simples descriptions textuelles m'a fait gagner un temps précieux. Hautement recommandé !",
    img: "./images/humain/personne-8.jpg",
  },
  {
    name: "Chloé Robert",
    username: "@chloe_crea",
    body: "L'interface intuitive de VizHome et sa précision dans la modélisation 3D en font un outil exceptionnel. Que ce soit à partir d'une image ou d'un texte, les résultats sont toujours au rendez-vous.",
    img: "./images/humain/personne-9.jpg",
  },
  {
    name: "Alexandre Fontaine",
    username: "@alex_fonte",
    body: "VizHome a dépassé mes attentes. La qualité des modèles 3D générés est remarquable, et la possibilité de travailler à partir de descriptions textuelles ouvre de nouvelles perspectives créatives.",
    img: "./images/humain/personne-10.jpg",
  },
  {
    name: "Manon Gauthier",
    username: "@manon_design",
    body: "Pour tous ceux qui cherchent à intégrer rapidement des modèles 3D dans leurs projets, VizHome est la solution idéale. Sa technologie basée sur l'IA est à la fois puissante et facile à utiliser.",
    img: "./images/humain/personne-11.jpg",
  },
  {
    name: "Nicolas Roy",
    username: "@nicolas_art",
    body: "La capacité de VizHome à convertir des descriptions textuelles en modèles 3D précis est tout simplement incroyable. C'est un outil révolutionnaire pour les créateurs de contenu.",
    img: "./images/humain/personne-12.jpg",
  },
  {
    name: "Claire Lefebvre",
    username: "@claire_archi",
    body: "VizHome est une révolution dans le domaine de la modélisation 3D. Sa capacité à transformer des images et des descriptions textuelles en modèles 3D précis est impressionnante. Un outil indispensable pour les designers et les architectes.",
    img: "./images/humain/personne-13.jpg",
  },
  {
    name: "Hugo Lambert",
    username: "@hugo_dev",
    body: "En tant que développeur de jeux vidéo, VizHome a simplifié mon flux de travail. La génération rapide de modèles 3D à partir de simples descriptions textuelles m'a fait gagner un temps précieux. Hautement recommandé !",
    img: "./images/humain/personne-14.jpg",
  },
  {
    name: "Léa Fournier",
    username: "@lea_crea",
    body: "L'interface intuitive de VizHome et sa précision dans la modélisation 3D en font un outil exceptionnel. Que ce soit à partir d'une image ou d'un texte, les résultats sont toujours au rendez-vous.",
    img: "./images/humain/personne-15.jpg",
  },
  {
    name: "Mathieu Girard",
    username: "@mathieu_innov",
    body: "VizHome a dépassé mes attentes. La qualité des modèles 3D générés est remarquable, et la possibilité de travailler à partir de descriptions textuelles ouvre de nouvelles perspectives créatives.",
    img: "./images/humain/personne-16.jpg",
  },
];


// Split reviews into two rows
const firstRow = ref(reviews.slice(0, reviews.length / 2));
const secondRow = ref(reviews.slice(reviews.length / 2));


const features = [
  {
    icon: 'zap',
    title: 'Génération Instantanée',
    description: 'Transformez vos images en modèles 3D en quelques secondes grâce à notre IA avancée.'
  },
  {
    icon: 'target',
    title: 'Précision Exceptionnelle',
    description: 'Obtenez des modèles 3D précis avec des dimensions et des proportions parfaites.'
  },
  {
    icon: 'refresh-cw',
    title: 'Export Flexible',
    description: 'Exportez vos modèles dans tous les formats courants de l industrie.'
  }
]

</script>

<!-- 
<script setup>
const features = [
  {
    icon: 'zap',
    title: 'Génération Instantanée',
    description: 'Transformez vos images en modèles 3D en quelques secondes grâce à notre IA avancée.'
  },
  {
    icon: 'target',
    title: 'Précision Exceptionnelle',
    description: 'Obtenez des modèles 3D précis avec des dimensions et des proportions parfaites.'
  },
  {
    icon: 'refresh-cw',
    title: 'Export Flexible',
    description: 'Exportez vos modèles dans tous les formats courants de l industrie.'
  }
]

const testimonials = [
  {
    initial: 'ML',
    name: 'Marie Laurent',
    role: 'Architecte Senior',
    quote: 'ArchVision AI a transformé notre façon de travailler. La précision et la rapidité sont impressionnantes.'
  },
  {
    initial: 'TD',
    name: 'Thomas Dubois',
    role: 'Designer d\'Intérieur',
    quote: 'Un outil révolutionnaire qui nous fait gagner des heures de modélisation.'
  },
  {
    initial: 'SC',
    name: 'Sophie Cohen',
    role: 'Directrice de Projet',
    quote: 'La qualité des modèles générés dépasse toutes nos attentes. Un must-have.'
  }
]
</script>

<style>
.bg-grid-white\/5 {
  background-size: 40px 40px;
  background-image: linear-gradient(to right, rgba(255, 255, 255, 0.05) 1px, transparent 1px),
    linear-gradient(to bottom, rgba(255, 255, 255, 0.05) 1px, transparent 1px);
}

.animate-fade-in {
  animation: fadeIn 1s ease-out;
}

@keyframes fadeIn {
  from {
    opacity: 0;
    transform: translateY(20px);
  }
  to {
    opacity: 1;
    transform: translateY(0);
  }
}

/* Ajout d'un effet de hover élégant sur les cartes */
.i-card {
  transition: transform 0.3s ease, box-shadow 0.3s ease;
}

.i-card:hover {
  transform: translateY(-5px);
  box-shadow: 0 20px 40px -15px rgba(0, 0, 0, 0.3);
}
</style> -->